### ISSUE TITLE
When building on release (not debug??) the icon in the top left is gone (????????)

### ISSUE THREAD

**Issue by shef3r** [shef3r/Transhef#1]
Release:
![image](https://github.com/shef3r/Transhef/assets/79228174/fb864bec-3bca-4206-bba4-cb4442c849af)

Debug:
![image](https://github.com/shef3r/Transhef/assets/79228174/1b67e813-a4bf-4982-a6fc-268a231e0afb)

**Comment by errortek** [comment]
> Release: ![image](https://private-user-images.githubusercontent.com/79228174/300917545-fb864bec-3bca-4206-bba4-cb4442c849af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzgyMDgsIm5iZiI6MTcxNDY3NzkwOCwicGF0aCI6Ii83OTIyODE3NC8zMDA5MTc1NDUtZmI4NjRiZWMtM2JjYS00MjA2LWJiYTQtY2I0NDQyYzg0OWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE5MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZTFlNDFhODA4YWY4YzljYjFhNTYxYWY2NDU4ZjEwYTBmMGNkNGFmNWQ5OTUwYzAyNzMzMWQ1NDZkYzRmMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0_puVcYkyS1qdnYvuOso2Hz3iYasDODVTwt8XOKYRo)
> 
> Debug: ![image](https://private-user-images.githubusercontent.com/79228174/300917711-1b67e813-a4bf-4982-a6fc-268a231e0afb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzgyMDgsIm5iZiI6MTcxNDY3NzkwOCwicGF0aCI6Ii83OTIyODE3NC8zMDA5MTc3MTEtMWI2N2U4MTMtYTRiZi00OTgyLWE2ZmMtMjY4YTIzMWUwYWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE5MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYmNjZjBlMTQ2Nzk1YjJiYTIxYjY3NDI1ZjBiZWExN2Y3MDA2MTJiYjdjYzA4MjUxYzNlYzA2N2QxMWE3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V2kZRqI-RNrwxZcmoVnjPHgMo_VAmmJ3DmHZUt2julk)

This is a great app, well done!
Just saying that the Assets folder (which most commonly contains resources like the app icon) does not get copied over to release variants/release folders by default (I've encountered the same problem myself), so just copy the Assets folder from the source into the folder where the Release compile is and it should work (the icon should show)!
Have a nice day!

**Comment by shef3r** [comment]
Thank you for the comment!! It'll get resolved soon!

**Comment by shef3r** [comment]
Thanks for the comment! I'm not sure what you mean though. Where's the release folder?

**Comment by errortek** [comment]
> Thanks for the comment! I'm not sure what you mean though. Where's the release folder?

The release folder is where the "Release" variant of your app is saved to.
This is the path of the folder of the "Release" configuration on a WinUI3 app I develop:
![image](https://github.com/shef3r/Transhef/assets/100033309/6ceeb849-9950-4cc3-868b-61aaecca57f3)
I think it's the default path (of course net8.0-windows10.0.22621.0 depends on the TFM your app has - which .NET version it uses and which Windows SDK it targets. In this case, the .NET version it uses is .NET 8, hence the .net8.0 in the directory name, and it targets the Windows 11 22H2 (build 22621) SDK, hence the windows10.0.22621.0 in the directory name.)
When you run a Release build of your app, you should be able to get to the actual directory of the compile (note that this method only works if the release compile is currently running, either standalone with no debugger, or with the vs debugger enabled) by right-clicking on your app's icon on the taskbar then right-clicking the icon on the flyout, then selecting properties and open file location, which will lead you to the actual directory where your release compile is stored.

(if you want to talk to me in more depth about this, feel free to message me on my Discord acc (alternatively just ping me in dev sanx in your project channel), my username there is jpb_errortek btw!)

Hope this helps,
jpbandroid

**Comment by shef3r** [comment]
Fixed in v1 🫶
