### ISSUE TITLE
Required Dependencies Are Not Available

### ISSUE THREAD

**Issue by D-Maxwell** [shef3r/Transhef#2]
hello there ;

I find myself in quite the bind as, upon installing the app package, it asks for the WINUI library (UI.XAML) version to exceed 2.8.2310.30001.0, when only 2.8.2306.22001.0 seems to be available from WinGet.

The reason I must bother with this in the first place is that, like all other standard AppX packages, the regular installer crashes. (this is not an issue of yours)

Is it absolutely required for the app to ask for such a recent version ? Could the dependency requirements perhaps be lowered ?
Or even better, would it be possible to supply the dependencies (or links to them) ?

**Comment by shef3r** [comment]
I'll give you the link, but the default App Installer (comes with Windows) should download them automatically from the Microsoft Store anyway, and that's the way I suggest installing the app. Assuming you use a 64-bit machine, here are the dependencies in a ZIP file. 

[deps.zip](https://github.com/shef3r/Transhef/files/14116882/deps.zip)
